// Demo data seeding — populates a fresh (empty) database with a varied set of
// Islamic-themed memories (Qur'an, Arabic vocabulary, hadith, fiqh, seerah)
// spread across different "learned" dates and FSRS review histories, so the
// app is immediately populated and every page (Memory, Schedule, Review,
// Insights) has something real to show rather than empty states.
//
// Review history is generated by actually running memories through the real
// FSRS engine (schedule()) rather than hand-faking card state, so the
// resulting due dates, stability, difficulty and retention numbers are
// internally consistent with how the app would have produced them.

import { CardState, Rating, DEFAULT_SETTINGS } from "../core/types";
import type { Memory, ReviewLogEntry } from "../core/types";
import { createNewCard, schedule } from "../fsrs/engine";
import { dbPutMany, STORES } from "./database";
import { ensureCollection } from "./repository";
import { addDays } from "../core/dates";

function uid(prefix: string): string {
  return prefix + "_" + Date.now().toString(36) + Math.random().toString(36).slice(2, 10);
}

interface SeedSpec {
  content: string;
  prompt?: string;
  answer?: string;
  collection: string;
  tags: string[];
  learnedDaysAgo: number; // how many days ago this was learned
  // Simulated review ratings applied in order, spaced realistically, to
  // build up genuine FSRS state. Empty = still New.
  reviewRatings: Rating[];
}

const SEED_SPECS: SeedSpec[] = [
  {
    content: "Ayat al-Kursi — Al-Baqarah, Ayah 255",
    prompt: "Recite Ayat al-Kursi",
    answer: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ...",
    collection: "Qur'an",
    tags: ["al-baqarah", "memorization"],
    learnedDaysAgo: 34,
    reviewRatings: [Rating.Good, Rating.Good, Rating.Easy, Rating.Good, Rating.Good],
  },
  {
    content: "Surah Al-Ikhlas — full surah",
    prompt: "Recite Surah Al-Ikhlas",
    answer: "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
    collection: "Qur'an",
    tags: ["short-surah", "memorization"],
    learnedDaysAgo: 60,
    reviewRatings: [Rating.Good, Rating.Easy, Rating.Easy, Rating.Good, Rating.Easy, Rating.Good],
  },
  {
    content: "Surah Al-Fatiha — meaning of 'Ihdina as-sirat al-mustaqim'",
    prompt: "What does 'اهدنا الصراط المستقيم' mean?",
    answer: "Guide us to the straight path",
    collection: "Qur'an",
    tags: ["al-fatiha", "tafsir"],
    learnedDaysAgo: 12,
    reviewRatings: [Rating.Good, Rating.Hard, Rating.Good],
  },
  {
    content: "Ayah on patience — 'Inna Allaha ma'as-sabirin'",
    prompt: "Complete: 'إِنَّ اللَّهَ مَعَ...'",
    answer: "الصَّابِرِينَ — Indeed, Allah is with the patient (Al-Baqarah 2:153)",
    collection: "Qur'an",
    tags: ["patience", "al-baqarah"],
    learnedDaysAgo: 5,
    reviewRatings: [Rating.Good],
  },

  {
    content: "كان — was / became",
    prompt: "Translate: كان",
    answer: "was / became (a defective/hollow verb — kāna)",
    collection: "Arabic",
    tags: ["vocab", "verbs"],
    learnedDaysAgo: 21,
    reviewRatings: [Rating.Good, Rating.Good, Rating.Easy, Rating.Good],
  },
  {
    content: "علم — knowledge",
    prompt: "Translate: علم",
    answer: "knowledge ('ilm)",
    collection: "Arabic",
    tags: ["vocab", "noun"],
    learnedDaysAgo: 8,
    reviewRatings: [Rating.Good, Rating.Good],
  },
  {
    content: "استغفر — to seek forgiveness",
    prompt: "Translate: استغفر",
    answer: "to seek forgiveness (istaghfara, form X of غفر)",
    collection: "Arabic",
    tags: ["vocab", "form-x"],
    learnedDaysAgo: 3,
    reviewRatings: [Rating.Hard],
  },
  {
    content: "الرحمن vs الرحيم — difference in meaning",
    prompt: "What's the nuance between الرحمن and الرحيم?",
    answer: "Ar-Rahman: mercy encompassing all creation; Ar-Rahim: mercy specifically for believers",
    collection: "Arabic",
    tags: ["grammar", "names-of-allah"],
    learnedDaysAgo: 45,
    reviewRatings: [Rating.Good, Rating.Again, Rating.Hard, Rating.Good, Rating.Good],
  },
  {
    content: "Root ك-ت-ب (k-t-b) — family of words",
    prompt: "Name three words from the root ك-ت-ب",
    answer: "كتاب (book), كاتب (writer), مكتبة (library)",
    collection: "Arabic",
    tags: ["roots", "vocab"],
    learnedDaysAgo: 15,
    reviewRatings: [Rating.Good, Rating.Good],
  },

  {
    content: "Hadith — 'Actions are judged by intentions'",
    prompt: "Complete the hadith: 'Innamal a'malu...'",
    answer: "بالنيات — Actions are judged by intentions (Bukhari & Muslim, opening hadith of the 40 Nawawi)",
    collection: "Hadith",
    tags: ["nawawi-40", "intentions"],
    learnedDaysAgo: 28,
    reviewRatings: [Rating.Good, Rating.Easy, Rating.Good, Rating.Good],
  },
  {
    content: "Hadith — the believer's example is like a palm tree",
    prompt: "What is the believer compared to in this hadith?",
    answer: "A palm tree (nakhlah) — nothing from it goes to waste",
    collection: "Hadith",
    tags: ["parables"],
    learnedDaysAgo: 9,
    reviewRatings: [Rating.Good],
  },
  {
    content: "Hadith on kindness to parents ranking after prayer",
    prompt: "What deed did the Prophet ﷺ rank right after prayer on time?",
    answer: "Kindness/dutifulness to parents (birr al-walidayn)",
    collection: "Hadith",
    tags: ["parents", "adab"],
    learnedDaysAgo: 2,
    reviewRatings: [],
  },

  {
    content: "The five pillars of Islam, in order",
    prompt: "List the five pillars of Islam",
    answer: "Shahada, Salah, Zakah, Sawm, Hajj",
    collection: "Fiqh",
    tags: ["pillars", "basics"],
    learnedDaysAgo: 70,
    reviewRatings: [Rating.Easy, Rating.Easy, Rating.Good, Rating.Easy, Rating.Easy, Rating.Good],
  },
  {
    content: "Conditions that break wudu",
    prompt: "Name three things that break wudu",
    answer: "Using the toilet, passing wind, deep sleep (among others)",
    collection: "Fiqh",
    tags: ["taharah", "wudu"],
    learnedDaysAgo: 18,
    reviewRatings: [Rating.Good, Rating.Hard],
  },
  {
    content: "Nisab threshold for Zakah on gold",
    prompt: "What is the nisab for gold (approx.)?",
    answer: "85 grams of gold",
    collection: "Fiqh",
    tags: ["zakah"],
    learnedDaysAgo: 6,
    reviewRatings: [Rating.Good],
  },
  {
    content: "Times during which prayer is disliked (makruh)",
    collection: "Fiqh",
    tags: ["salah", "timing"],
    learnedDaysAgo: 1,
    reviewRatings: [],
  },

  {
    content: "The Prophet ﷺ's migration (Hijrah) — from Makkah to Madinah",
    prompt: "In which year did the Hijrah take place (Islamic calendar epoch)?",
    answer: "622 CE — Year 1 of the Hijri calendar",
    collection: "Seerah",
    tags: ["hijrah", "timeline"],
    learnedDaysAgo: 40,
    reviewRatings: [Rating.Good, Rating.Good, Rating.Good],
  },
  {
    content: "The Companion who was the first to embrace Islam among men",
    prompt: "Who was the first adult man to accept Islam?",
    answer: "Abu Bakr as-Siddiq (ra)",
    collection: "Seerah",
    tags: ["companions"],
    learnedDaysAgo: 25,
    reviewRatings: [Rating.Good, Rating.Good],
  },
  {
    content: "Battle of Badr — year and significance",
    prompt: "When was Badr fought and why was it significant?",
    answer: "2 AH — first major military victory for the young Muslim community",
    collection: "Seerah",
    tags: ["battles", "timeline"],
    learnedDaysAgo: 0,
    reviewRatings: [],
  },

  {
    content: "Capital of Kazakhstan is Astana",
    collection: undefined as unknown as string,
    tags: [],
    learnedDaysAgo: 4,
    reviewRatings: [Rating.Good],
  },
];

export async function seedDemoData(): Promise<void> {
  const now = new Date();
  const memories: Memory[] = [];
  const logs: ReviewLogEntry[] = [];

  for (const spec of SEED_SPECS) {
    const learnedAt = addDays(now, -spec.learnedDaysAgo);
    learnedAt.setHours(9, 0, 0, 0);

    let card = createNewCard(learnedAt);
    // Simulate the passage of time between the learn date and now, applying
    // each review at a sensible point along that span so ratings land on
    // distinct, plausible days rather than all at once.
    const now_ = now.getTime();
    const span = Math.max(1, spec.learnedDaysAgo);
    const memoryId = uid("mem");

    spec.reviewRatings.forEach((rating, i) => {
      const fraction = (i + 1) / (spec.reviewRatings.length + 1);
      const reviewTime = new Date(
        learnedAt.getTime() + fraction * (now_ - learnedAt.getTime())
      );
      const result = schedule(card, rating, reviewTime, DEFAULT_SETTINGS);
      logs.push({
        id: uid("rev"),
        memoryId,
        rating,
        state: result.card.state,
        due: result.card.due,
        stability: result.card.stability,
        difficulty: result.card.difficulty,
        elapsedDays: result.logPreview.elapsedDays,
        lastElapsedDays: result.logPreview.lastElapsedDays,
        scheduledDays: result.logPreview.scheduledDays,
        reviewedAt: reviewTime.toISOString(),
        reviewAhead: false,
      });
      card = result.card;
    });

    const createdAt = learnedAt.toISOString();
    memories.push({
      id: memoryId,
      content: spec.content,
      prompt: spec.prompt,
      answer: spec.answer,
      tags: spec.tags,
      collection: spec.collection || undefined,
      type: undefined,
      createdAt,
      learnedAt: createdAt,
      updatedAt: new Date().toISOString(),
      completed: false,
      archived: false,
      deleted: false,
      card,
    });
  }

  await dbPutMany(STORES.memories, memories);
  await dbPutMany(STORES.reviewLog, logs);

  const collectionNames = Array.from(
    new Set(memories.map((m) => m.collection).filter((c): c is string => !!c))
  );
  for (const name of collectionNames) {
    await ensureCollection(name);
  }
}
